paths:
  /api/products:
    get:
      summary: Obtener todos los productos que cumplan con la query
      tags:
        - Products
      responses:
        "200":
          description: Los productos se obtienen de la base de datos
        "500": 
          description: Error del servidor
    post:
      summary: Crear un producto
      tags:
        - Products
      responses:
        "200":
          description: El producto fue creado exitosamente
        "404":
          description: Algunos datos obligatorios no fueron completados
        "500": 
          description: Error del servidor
  /api/products/:pid:
    get:
      summary: Obtener producto por ID
      tags:
        - Products
      responses:
        "200":
          description: Producto Obtenido de la base de datos
        "404":
          description: El producto no existe
        "500":
          description: Error del servidor
    put:
      summary: Modificar el producto 
      tags:
        - Products
      responses:
        "200":
          description: El producto fue modificado exitosamente
        "400":
          description: El producto no existe
        "401":
          description: El producto no pertenece al usuario
        "500": 
          description: Error del servidor
    delete:
      summary: Eliminar el producto
      tags:
        - Products
      responses:
        "200":
          description: El producto fue eliminado exitosamente
        "400":
          description: El producto no existe
        "401":
          description: El producto no es del usuario que trata de eliminarlo
        "500": 
          description: Error del servidor


components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado
        title:
          type: String
          description: Titulo del producto
        description:
          type: String
          description: Descripcion
        price:
          type: Number
          description: Precio por unidad
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Cantidad de productos disponibles para la venta
        thumbnails:
          type: Array
          description: Arreglo de ids de carritos
          items:
            type: String
            description: URL de la imagen del producto
        category:
          type: String
          description: Categoria del producto
        owner:
          type: String
          description: Usuario dueño del producto
      example:
        _id: "63e41ebb7c18d64e82481157"
        title: Producto2
        description: Segundo producto
        price: 200
        code: abc2
        stock: 20
        thumbnails: []
        category: b
        owner: admin